# To learn about plugin YAML attributes, visit: http://wiki.bukkit.org/Plugin_YAML or https://www.spigotmc.org/wiki/plugin-yml/
# To learn about semantic versioning, visit: https://semver.org
main: org.example.plugin.Plugin
version: 1.0.0
name: INSERT_NAME
author: OPTIONAL_INSERT_AUTHOR
website: OPTIONAL_INSERT_WEBSITE
description: OPTIONAL_INSERT_DESCRIPTION